/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ATMSystem;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App(100000);
        assertNotNull("app should have a greeting", classUnderTest.greetings());
    }
}
