/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ATMSystem;

public class App {
    public String getGreeting() {
        return "XYZ Bank ATM";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
	//next line: DB db = new DB("<db-url>","<username>","<password>");
	DB db = new DB("alien","fuck","jdbc:postgresql://localhost:5432/a12412");
	db.authenticate("11111","0000");
	System.out.println(db.getCardNumber());
	db.setBalance(1000000.0);
    }
}
